Improved scripts

diff --git a/scripts/gen-initramfs b/scripts/gen-initramfs
--- a/scripts/gen-initramfs
+++ b/scripts/gen-initramfs
@@ -7,20 +7,32 @@
 #### Usage: gen-initramfs
 ####
 
-sources=(bin/mv bin/cp bin/umount bin/mount bin/mkdir bin/chroot bin/ls bin/rmdir bin/rm bin/mknod bin/bash bin/mkfifo lib/libc-2.20.so lib/libuuid.so.1.3.0 lib/libmount.so.1.1.0 lib/libattr.so.1 lib/libncursesw.so.5.9 lib/libblkid.so.1.1.0 sbin/switch_root sbin/pivot_root lib64/ld-linux-x86-64.so.2 lib64/libdl-2.20.so)
+# Source files are hard-linked, not copied, thus MUST NOT be modified
+sources=(bin/mv bin/cp bin/umount bin/mount bin/mkdir bin/chroot bin/ls bin/rmdir bin/rm bin/mknod bin/bash bin/mkfifo lib64/libc-2.20.so lib/libuuid.so.1.3.0 lib/libmount.so.1.1.0 lib/libattr.so.1 usr/lib/libncursesw.so.5.9 lib/libblkid.so.1.1.0 sbin/switch_root sbin/pivot_root lib64/ld-linux-x86-64.so.2 lib64/libdl-2.20.so)
 
 source $(dirname "$0")/dirs.inc.sh
+
+$(dirname "$0")/build-stage 1
 
 [[ ! -d "$INITRAMFS_DIR" ]] && echo "ERROR: initramfs directory not found." >&2 && exit 1
 
 pushd "$INITRAMFS_DIR" >/dev/null
 rm -rf *
 
-mkdir -p etc bin sbin lib
+mkdir -p etc bin sbin lib usr/lib usr/local/lib
 ln -s lib lib64
+ln -s lib usr/lib64
+ln -s lib usr/local/lib64
 
 for f in ${sources[*]}; do
-  cp "$ENV_DIR/$f" "$INITRAMFS_DIR/$f"
+  cp -l "$ENV_DIR/$f" "$INITRAMFS_DIR/$f"
 done
 
 popd >/dev/null
+
+if ! $(dirname "$0")/gen-cpio-index; then
+  echo "Unable to generate cpio index" >&2
+  exit 1
+fi
+
+make -C $(find $(dirname "$0")/../ -maxdepth 1 -name 'linux-*' -type d)
