Improved script files

diff --git a/scripts/kernel-install b/scripts/kernel-install
--- a/scripts/kernel-install
+++ b/scripts/kernel-install
@@ -11,10 +11,8 @@
 #### kernel-version is the complete kernel version, i.e.: 3.13.3
 ####
 
+source $(dirname "$0")/dirs.inc.sh
 exec 3>/dev/null
-
-# Constants
-PKG_DIR=/tmp/pkg
 
 # Arguments
 KNL_VER="$1"
@@ -32,16 +30,16 @@ KNL_OUT_FILE="vmlinuz-${KNL_VER}-wise"
 # Create directories
 echo "Populating directory hierarchy..."
 
-mkdir -p ${PKG_DIR}/{boot,lib} || (echo "ERROR: unable to create directory structure" && exit 2)
+mkdir -p ${BLD_DIR}/{boot,lib} || (echo "ERROR: unable to create directory structure" && exit 2)
 
 # Install files
 echo "Installing kernel files..."
-cp "${KNL_DIR}/arch/x86/boot/bzImage" "${PKG_DIR}/boot/${KNL_OUT_FILE}"
-cp "${KNL_DIR}/System.map" "${PKG_DIR}/boot/"
-make -C "${KNL_DIR}" INSTALL_MOD_PATH=${PKG_DIR} modules_install >&3
+cp "${KNL_DIR}/arch/x86/boot/bzImage" "${BLD_DIR}/boot/${KNL_OUT_FILE}"
+cp "${KNL_DIR}/System.map" "${BLD_DIR}/boot/"
+make -C "${KNL_DIR}" INSTALL_MOD_PATH=${BLD_DIR} modules_install >&3
 
 # Create links
-pushd "${PKG_DIR}/boot" >&3
+pushd "${BLD_DIR}/boot" >&3
 ln -s ${KNL_OUT_FILE} vmlinuz >&3
 popd >&3
 
diff --git a/scripts/pack b/scripts/pack
--- a/scripts/pack
+++ b/scripts/pack
@@ -12,19 +12,16 @@
 #### stage# is the stage number (1, 2 or 3)
 #### pack-name is the package name (e.g.: linux-3.13.3)
 
+source $(dirname "$0")/dirs.inc.sh
 exec 3>/dev/null
-
-# Constants
-PKG_DIR="/tmp/pkg"
-DEV_DIR=~/linux/pkgs
 
 # Set args
 STAGE=$1
 PKG_NAME=$2
-STAGE_DIR="${DEV_DIR}/stage${STAGE}"
+STAGE_DIR="${PKG_DIR}/stage${STAGE}"
 
 # Check environment
-[[ ! -d "$PKG_DIR" ]] && echo "ERROR: Packaging directory <${PKG_DIR}> does not exist" >&2 && exit 1
+[[ ! -d "$BLD_DIR" ]] && echo "ERROR: Packaging directory <${BLD_DIR}> does not exist" >&2 && exit 1
 [[ ! -d "$STAGE_DIR" ]] && echo "ERROR: Stage directory <${STAGE_DIR}> does not exist" >&2 && exit 1
 
 # Check args
@@ -48,19 +45,19 @@ echo "Creating package ${PKG_FILE}:"
 # Compress package
 echo "- Compressing..."
 
-pushd "${PKG_DIR}" >&3
+pushd "${BLD_DIR}" >&3
 (tar --recursion -cJvf "$PKG_PATH" * | awk '{ print ">> " $0; }') || (echo "ERROR: Unable to create compressed tarball" >&2 && exit 2)
 popd >&3
 
 echo
 # Display size stats
 echo -n "- * Original size: "
-du -h "$PKG_DIR" | tail -n 1 | awk '{ print $1; }'
+du -h "$BLD_DIR" | tail -n 1 | awk '{ print $1; }'
 echo -n "- * Packed size: "
 du -h "$PKG_PATH" | awk '{ print $1; }'
 
 echo
 # Clean-up
 echo "- Cleaning up..."
-rm -rf ${PKG_DIR}/*
+rm -rf ${BLD_DIR}/*
 
